services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: mtx-app-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: mtx-app-client
    depends_on:
      - api
    ports:
      - "3000:80"